### ISSUE TITLE
Error 403 libraries.minecraft.net

### ISSUE THREAD

**Issue by Inglebard** [bspkrs/Treecapitator#28]
Hi,

I would like to build your mod.
Build always fail  because it try to download bscore pom file from https://libraries.minecraft.net/ but return 403.

How can I fix it ?

**Comment by bspkrs** [comment]
Replace the beginning of the URL with http://bspk.rs. Everything before /MC/

**Comment by Inglebard** [comment]
Hi,

I follow your documentation, here is my output when i do `gradle build`  : 

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve :bspkrsCore:6.15.
  Required by:
      treecapitator:Treecapitator:2.0.4
   > Could not GET 'https://libraries.minecraft.net//bspkrsCore/6.15/bspkrsCore-6.15.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


Where am i suppose to change the url ?

**Comment by bspkrs** [comment]
You'll change the URL in the build.gradle file. Everything before the /MC/... in the URL for bspkrsCore should change to http://bspk.rs

**Comment by bspkrs** [comment]
Ok, I just tried it and got the same error... looking into it now.

**Comment by Inglebard** [comment]
Thanks, It works well now.
Use a wrapper is a good idea because gradle is not in Ubuntu 14.04 default repositories.

Just need to edit documentation for new people which want to build your mod.

Thanks, nice job and nice mod.
