### ISSUE TITLE
[Feature request] Ex Nihilo

### ISSUE THREAD

**Issue by Maelstraz** [bspkrs/Treecapitator#29]
Iirc, there is feature for auto-use shears, if you have it in your inventory, while treecapitating.

So, can you add same mechanic for Ex Nihilo's crooks?

**Comment by bspkrs** [comment]
You have the ability to add them to the config file if you so desire.

**Comment by Lunatrius** [comment]
Won't work. The crook uses `onBlockStartBreak` instead of `onBlockDestroyed`.
