### ISSUE TITLE
Treecapitor seems to like breaking stuff, huh?

### ISSUE THREAD

**Issue by Wuerfel21** [bspkrs/Treecapitator#30]
Well, i got reports of my mods trees crashing treecapitor.
I think it might be related to https://github.com/Wuerfel21/The-Derpy-Shiz-Mod/blob/master/src/main/java/net/wuerfel21/derpyshiz/DerpyEvents.java#L95-L110

**Comment by bspkrs** [comment]
Why would you add drops to your own block using a general event that fires for every block..? That sort of code belongs in your block class.

Without any sort of stacktrace or log file, there's really nothing that I'm willing to do about this crash that you claim is my fault.

**Comment by nekosune** [comment]
The three override methods on your blocks you want are
    
    @Override
    public Item getItemDropped(int meta, Random random, int fortune) {
        returns the item to drop
    }

    @Override
    public int damageDropped(int metadata) {
        return the meta value of the item dropped
    }

    @Override
    public int quantityDropped(int meta, int fortune, Random random) {
       // return amount of the items
    }

That will work for all but your darkness one

**Comment by bspkrs** [comment]
As nekosune discovered, this crash is on your side and can be achieved with ONLY your mod installed by placing TNT next to an Ebony tree and igniting it. https://pastebin.com/gjirVgJW
